vich_uploader:
    db_driver: orm

    mappings:
        image_sponsor:
            uri_prefix: /uploads/images/sponsors
            upload_destination: '%kernel.project_dir%/public/uploads/images/sponsors'
