vich_uploader:
  db_driver: orm

  mappings:
    image_sponsor:
      uri_prefix: /uploads/images/sponsors
      upload_destination: '%kernel.project_dir%/public/uploads/images/sponsors'

    image_gallery:
      uri_prefix: /uploads/images/gallery
      upload_destination: '%kernel.project_dir%/public/uploads/images/gallery'

    image_event:
      uri_prefix: /uploads/images/event
      upload_destination: '%kernel.project_dir%/public/uploads/images/event'

